### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by jacampo** [voidful/BDG#1]
Hello, I'm looking for some project to see what can be done in this topic. Do you have the trained distractor generation model? It could be interesting in order to try a demo, or a colab notebook with some results. That could be really helpful. How long did you trained the model?

Thanks in advance.

**Comment by voidful** [comment]
Do you have the trained distractor generation model
> Hopefully, as soon as possible, we're still looking for a place for model hosting.

It could be interesting in order to try a demo, or a colab notebook with some results.
> Our final result: https://voidful.tech/DG-Showcase/

How long did you trained the model
> It took about 8 hours for 1 epoch in RTX titan

**Comment by jacampo** [comment]
Thanks for the response, I'll take a look at the result

**Comment by voidful** [comment]
> Thanks for the response, I'll take a look at the result
I‘ve uploaded model on Github release
https://github.com/voidful/BDG/releases/tag/v1.0

here is a colab notebook for your reference
https://colab.research.google.com/drive/1yA3Rex9JHKJmc52E3YdsBQ4eQ_R6kEZB?usp=sharing
