### ISSUE TITLE
Error when running Colab demo

### ISSUE THREAD

**Issue by LeeJoonJie** [voidful/BDG#4]
Hi, I encountered an error when running your provided Colab notebook.

![Screenshot 2021-06-23 at 10 36 47 AM](https://user-images.githubusercontent.com/48320865/123026660-237e2680-d40f-11eb-8431-2c4927c2f992.png)

**Comment by voidful** [comment]
I am sorry for the error, I made a few changes on the library few days ago. I should lock the package version on colab. 
It's fixed now.

**Comment by LeeJoonJie** [comment]
Thank you! It is working now
