### ISSUE TITLE
Error when running the demo

### ISSUE THREAD

**Issue by Tikook** [voidful/BDG#5]
Thank you for sharing the project. I have encountered an error when running the ([https://github.com/voidful/BDG/blob/main/BDG_selection.ipynb].)  I can't get the choices with ['result'] in prediction which shows keyerror. And when I print the choices it shows the error "Attention mask should be of size (1, 1, 1, 3), but is torch.Size([1, 1, 1, 1])".

Could you please help me with this?

**Comment by voidful** [comment]
When the decoder caching and beamsearch are used at the same time, errors will occur.
It has been fixed, please update to the latest version of nlp2go.

**Comment by Tikook** [comment]
Thank you! It works.
